### ISSUE TITLE
[Feature Request] Run immediately

### ISSUE THREAD

**Issue by jamesst20** [ealmansi/set-interval-async#18]
Hi,

A nice feature that I am missing from this library is a run immediately before the interval. I currently use a wrapper around your library to make this possible, however, it would be nice to have it built-in.

Thank you

Just leaving the wrapper I'm using in the mean time. I'm aware the dynamic behavior is not enforced until the second call

```
import { setIntervalAsync, SetIntervalAsyncTimer } from "set-interval-async/dynamic";


const SetIntervalNowAsync = (handler: (...args: any[]) => any, interval: number, ...args: any[]): SetIntervalAsyncTimer => {
  let ready = false;

  Promise.resolve(handler()).then(() => ready = true);

  const safeHandler = () => {
    if (ready) {
      return handler();
    }
  };

  return setIntervalAsync(safeHandler, interval, ...args);
}

export { SetIntervalNowAsync as setIntervalAsync };

```

**Comment by ealmansi** [comment]
Hi James,

Thanks for creating this issue; I appreciate it.

Like you pointed out, the snippet above slightly breaks the API. In particular, if the first execution takes longer than the interval to execute, the following property is no longer withheld:

> **Dynamic**: If possible, the given function is called once every interval milliseconds. If any execution takes longer than the desired interval, the next execution is delayed until the previous one has finished, and called immediately after this condition is reached.

Also, if the first execution fails, the process would be interrupted entirely.

I think the best way to achieve this would be changing this line in the definition of `setIntervalAsync`:
```javascript
  timer.timeouts[id] = setTimeout(
    timeoutHandler,
    0, // interval,
    timer,
    handler,
    interval,
    ...args
  )
```

I would be skeptical of adding in this feature if it implies a departure from the traditional `setInterval` API, since compatibility is one of the mail goals for the project.

**Comment by jamesst20** [comment]
Thanks for getting back to me.

I understand the drawback from moving away from the original API. A possible workaround could be to export an additional method ?

Exemple usage:

```
import { setIntervalAsync, setIntervalNowAsync, SetIntervalAsyncTimer } from "set-interval-async/dynamic";
```

**Comment by jamesst20** [comment]
@ealmansi 

Sorry, I have been lazy and hadn't taken the time to check your implementation. I found a way my feature request could be implemented without any breaking API changes.

Example for dynamic.js

Current implementation:
```
function setIntervalAsync (handler, interval, ...args) {
  validateHandler(handler)
  validateInterval(interval)
  const timer = new SetIntervalAsyncTimer()
  const iterationId = 0
  timer.timeouts[iterationId] = setTimeout(
    timeoutHandler,
    interval,
    timer,
    iterationId,
    handler,
    interval,
    ...args
  )
  return timer
}
```

becomes

```
function setIntervalAsync (handler, interval, ...args) {
  validateHandler(handler)
  validateInterval(interval)
  const timer = new SetIntervalAsyncTimer()
  const iterationId = 0
  const intervals = [interval].flat();
  timer.timeouts[iterationId] = setTimeout(
    timeoutHandler,
    intervals[0],
    timer,
    iterationId,
    handler,
    intervals[1] || intervals[0],
    ...args
  )
  return timer
}
```

No broken calls:

```
setIntervalAsync (() => {}, 1000, ...args)
setIntervalAsync (() => {}, [1000], ...args)
setIntervalAsync (() => {}, [0, 1000], ...args) // First run after 0ms and then 1000ms
```

**Comment by jamesst20** [comment]
@ealmansi  I opened a PR https://github.com/ealmansi/set-interval-async/pull/21

**Comment by nsdub** [comment]
This is a useful feature and one that I'd love to see merged. We're currently using @jamesst20 's solution with `patch-package`

**Comment by james-em** [comment]
Hi @ealmansi 

Have you had the chance to look into this pull request? I see the PR #21 was declined, perhaps you had a better idea in mind?

The interface

```
setIntervalAsync (() => {}, 1000, ...args) // Always after 1000ms
setIntervalAsync (() => {}, [0, 1000], ...args) // First run after 0ms and then 1000ms
```

looked pretty logical to me.

Waiting for your answer :)

**Comment by arthur-caillaud** [comment]
I also find the API in PR #21 quite good design actually. No breaking change and pretty straightforward. Did you find another solution @james-em or @jamesst20 for this feature ? Another package maybe ?

Thank you for your help

**Comment by james-em** [comment]
> lazy and hadn't taken the time to check your implementation. I found a way my feature request could be implemented without any breaking API changes.
> 
> Example for dynamic.js

I still use the same implementation proposed in #21 

I still don't understand why @ealmansi didn't merge it because it doesn't break anything and it was only one click away. We could have also exported extra method like setIntervalAsync, setIntervalNowAsync but looks like that proposition didn't sound good to him either.

**Comment by ealmansi** [comment]
While I understand that there's some interest in this feature, extending vanilla `setInterval` other than making it work nicely with async functions is beyond the scope of this library.
