### ISSUE TITLE
first method for es6 import not work in nodejs

### ISSUE THREAD

**Issue by cheluskin** [ealmansi/set-interval-async#28]
`import { setIntervalAsync } from 'set-interval-async/dynamic'`

internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_UNSUPPORTED_DIR_IMPORT]: Directory import '/Users/cheluskin/lf-server/node_modules/set-interval-async/dynamic' is not supported resolving ES modules imported from /Users/cheluskin/lf-server/index.js
Did you mean to import set-interval-async/dynamic/index.js?

**Comment by ealmansi** [comment]
Hi @cheluskin,

Thanks for your report. This issue should be solved with the latest version (v3.0.1).

Feel free to raise the issue again if you continue to experience this.
