### ISSUE TITLE
Any race condition ? Possibility to pause while inside the setIntervalAsync ?

### ISSUE THREAD

**Issue by iangregsondev** [ealmansi/set-interval-async#31]
Hi,

I am using this, works great. I have it set for 15 seconds. While I am inside the setIntervalAsync my async call (using async / await) can take a while - usually less than 15 seconds but still.. that means there would be a true 15 seconds between runs.

Is there some kind of ability to pause executions while inside setIntervalAsync - so to prevent race conditions and having a true 15 seconds between runs ?

Any idea if this is supported ?

Thanks in advance

**Comment by ealmansi** [comment]
Hi @iangregsondev ,

I'm not sure I understand your use case entirely but it appears like what you're describing is essentially the default behaviour of the library.

With the "fixed" strategy, the handler will be executed with a true interval of 15 seconds between runs
