### ISSUE TITLE
Error when running with Webpack 5

### ISSUE THREAD

**Issue by lopezvit** [ealmansi/set-interval-async#37]
When running the library with Webpack 5, there is a problem that prevents compiling:

> ERROR in ./node_modules/set-interval-async/fixed/index.mjs 7:0-72
> Module not found: Error: Can't resolve '@babel/runtime/helpers/asyncToGenerator' in '/Users/alejandrolopez/NodeJS/notecrow-forms-webapp/node_modules/set-interval-async/fixed'
> Did you mean 'asyncToGenerator.js'?
> BREAKING CHANGE: The request '@babel/runtime/helpers/asyncToGenerator' failed to resolve only because it was resolved as fully specified
> (probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
> The extension in the request is mandatory for it to be fully specified.
> Add the extension to the request.

This can be solved by upgrading the `@babel/runtime` to version `"^7.12.0"` (I don't understand why you fix the version to specific one instead of using the `^` version specification).

As a workaround (only works for **npm** version `>=8.3.0`) you can add this to your package.json:

```
  "overrides": {
    "@babel/runtime@": "^7.12.0"
  },
```

**Comment by ealmansi** [comment]
Hi @lopezvit, 

Thanks for your report. This issue should be solved with the latest version (v3.0.1).

Feel free to raise the issue again if you continue to experience this.
