### ISSUE TITLE
Handling computer sleep

### ISSUE THREAD

**Issue by cdosborn** [ealmansi/set-interval-async#4]
The browser's setInterval is oblivious to a computer sleeping. So if you have a 30min setInterval used to keep a token from expiring, the computer can wakeup, and think it still has 10 more minutes, even though hours have passed. 

I was hoping this package would handle something like this. Feel free to close if you're not interested. This is the solution I added, that could be adapted here:
```
const sleepAdjustedSetInterval = (handler, timeout, ...args) => {
  let baseTime = Date.now();
  const callHandler = () => {
    if (Date.now() - baseTime > timeout) {
      baseTime = Date.now();
      handler();
    }
  };
  return window.setInterval(callHandler, 1000, ...args);
};
```

**Comment by ealmansi** [comment]
hi @cdosborn , thanks for reaching out. One of the goals for this project is to keep the API as similar as possible to the built-in `setInterval` API, which has the same behaviour that you describe.
