### ISSUE TITLE
/node_modules/set-interval-async/dist/set-interval-async-timer.cjs:25

### ISSUE THREAD

**Issue by sauween** [ealmansi/set-interval-async#46]
<img width="990" alt="image" src="https://user-images.githubusercontent.com/53650420/186187331-c3ae1034-fcab-4c03-bd97-487e855d5ebd.png">
/node_modules/set-interval-async/dist/set-interval-async-timer.cjs:25
    #scheduleTimeout(strategy, handler, intervalMs, delayMs, ...handlerArgs) {
                    ^

SyntaxError: Unexpected token '('

/node_modules/set-interval-async/dist/set-interval-async-timer.cjs:33
    async #runHandlerAndScheduleTimeout(strategy, handler, intervalMs, ...handlerArgs) {
                                       ^

SyntaxError: Unexpected token '('

**Comment by ealmansi** [comment]
Hi @sauween 

Thanks for your report. Could you please share the following?

node version
set-interval-async version
snippet of code causing the issue

**Comment by sauween** [comment]
node -vv18.7.0

**Comment by ealmansi** [comment]
this seems to be due to a misconfigured bundler; if the issue persists feel free to ping here again with more details about how you are running/bundling your code

**Comment by franzwarning** [comment]
also seeing this fwiw
