### ISSUE TITLE
Can't import the named export 'clearIntervalAsync' (reexported as 'clearIntervalAsync') from default-exporting module (only default export is available)

### ISSUE THREAD

**Issue by mike-lischke** [ealmansi/set-interval-async#49]
Hi, after upgrading all my dependencies in my React (CRA) app, including `set-interval-async` I now get the error:

> Can't import the named export 'clearIntervalAsync' (reexported as 'clearIntervalAsync') from default-exporting module (only default export is available)

when building it. I checked the type definitions to see where that mentioned default export is, but couldn't find any. There are only named exports, so I'm a bit clueless now how to solve this import issue.

I'm using the latest version of `set-interval-async` (3.0.2), Node.js version 18.12.1 and this is my import line:

    import { clearIntervalAsync, setIntervalAsync, SetIntervalAsyncTimer } from "set-interval-async/dynamic";

**Comment by ealmansi** [comment]
unfortunately, it looks like create react app (CRA) does not handle ECMAScript modules (mjs files) correctly.

if you search for "create react app mjs" you will find many possible solutions, including [this one](https://github.com/reactioncommerce/reaction-component-library/issues/399#issuecomment-467860022) which works here for this library.

you just need to make sure that the test includes both cjs and mjs files:

```js
webpackConfig.module.rules.push({
  test: /\.(c|m)js$/,
  include: /node_modules/,
  type: "javascript/auto"
});
```
